"""
Migration 0037 must declare exactly what the models declare.

A model and its migration are two statements of the same schema, written in two
places. They drift silently: adding a column to a model and forgetting the
migration produces code that works locally against an autogenerated database
and fails in production the first time the column is read. Nothing else in this
repository catches that, and the failure arrives on the order path.

Parsed with `ast` from the migration source rather than executed, so this needs
no database and no Alembic context. It compares names only -- columns present,
indexes present, uniqueness -- which is the class of drift that actually
happens. Type changes are a different problem and are not claimed to be covered
here.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

from app.core.database import Base
# Importing the model modules is what registers them on the shared metadata.
from app.models import (  # noqa: F401
    broker_connection, messaging, oms_order, organization, trade_intent, user,
)

MIGRATION = (Path(__file__).resolve().parents[1]
             / "alembic" / "versions" / "0037_canonical_execution_records.py")

#: The tables 0037 is responsible for. Listed explicitly rather than derived,
#: so adding a model to a LATER migration cannot silently make this test
#: demand it here.
TABLES = (
    "trade_intents", "intent_evaluations", "approval_decisions",
    "oms_orders", "oms_order_legs", "oms_order_attempts", "oms_order_events",
    "oms_fills", "outbox_events", "inbox_receipts",
)


def _migration_schema() -> tuple[dict[str, set[str]], dict[str, tuple[str, tuple, bool]]]:
    """{table: {columns}}, {index_name: (table, columns, unique)} from the source."""
    tree = ast.parse(MIGRATION.read_text())
    tables: dict[str, set[str]] = {}
    indexes: dict[str, tuple[str, tuple, bool]] = {}

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
            continue
        if node.func.attr == "create_table" and node.args:
            name = ast.literal_eval(node.args[0])
            cols = set()
            for arg in node.args[1:]:
                if (isinstance(arg, ast.Call)
                        and getattr(arg.func, "attr", None) == "Column"
                        and arg.args):
                    cols.add(ast.literal_eval(arg.args[0]))
            tables[name] = cols
        elif node.func.attr == "create_index" and len(node.args) >= 3:
            ix_name = ast.literal_eval(node.args[0])
            table = ast.literal_eval(node.args[1])
            cols = tuple(ast.literal_eval(node.args[2]))
            unique = any(k.arg == "unique" and ast.literal_eval(k.value)
                         for k in node.keywords)
            indexes[ix_name] = (table, cols, unique)
    return tables, indexes


def test_the_scan_reads_the_migration():
    """Guards the guard: an AST walk that matched nothing would pass everything."""
    tables, indexes = _migration_schema()
    assert set(tables) == set(TABLES), (
        f"0037 creates {sorted(tables)}, expected {sorted(TABLES)}"
    )
    assert len(indexes) >= 10, f"only found {len(indexes)} indexes; the scan is broken"


@pytest.mark.parametrize("table_name", TABLES)
def test_migration_columns_match_the_model(table_name):
    migration_tables, _ = _migration_schema()
    model_cols = {c.name for c in Base.metadata.tables[table_name].columns}
    migration_cols = migration_tables[table_name]

    missing = model_cols - migration_cols
    extra = migration_cols - model_cols
    assert not missing, (
        f"{table_name}: the model declares {sorted(missing)} but the migration "
        "does not create it — reads of that column fail in production while "
        "passing against a locally autogenerated schema"
    )
    assert not extra, (
        f"{table_name}: the migration creates {sorted(extra)}, which no model "
        "declares — either the model lost a column or the migration gained one"
    )


def test_every_model_index_exists_in_the_migration():
    _, migration_indexes = _migration_schema()
    problems = []
    for table_name in TABLES:
        for ix in Base.metadata.tables[table_name].indexes:
            if ix.name not in migration_indexes:
                problems.append(f"{ix.name} ({table_name}) is missing from 0037")
                continue
            _, cols, unique = migration_indexes[ix.name]
            model_cols = tuple(c.name for c in ix.columns)
            if tuple(cols) != model_cols:
                problems.append(
                    f"{ix.name}: migration has {cols}, model has {model_cols}")
            if bool(unique) != bool(ix.unique):
                problems.append(
                    f"{ix.name}: unique={unique} in the migration, "
                    f"{ix.unique} in the model — this one is a CONSTRAINT, not "
                    "a performance hint")
    assert not problems, "\n  ".join(problems)


def test_the_idempotency_constraints_are_unique_indexes():
    """Named individually because these are the ones that stop duplicate orders.

    A reviewer can see a `create_index` call and not notice `unique=True` is
    absent; the result is a performance hint where a guarantee was intended,
    and nothing fails until two orders exist.
    """
    _, indexes = _migration_schema()
    required = {
        "idx_trade_intents_idempotency":
            ("trade_intents", ("organization_id", "command_type", "idempotency_key")),
        "idx_oms_orders_intent": ("oms_orders", ("intent_id",)),
        "idx_oms_fills_unique_execution":
            ("oms_fills", ("broker", "account_ref", "broker_execution_id")),
        "idx_oms_attempts_client_order_id":
            ("oms_order_attempts", ("client_order_id",)),
        "idx_oms_events_order_sequence": ("oms_order_events", ("order_id", "sequence")),
    }
    for name, (table, cols) in required.items():
        assert name in indexes, f"{name} is missing; duplicates become possible"
        got_table, got_cols, unique = indexes[name]
        assert got_table == table
        assert tuple(got_cols) == cols, f"{name}: scoped on {got_cols}, expected {cols}"
        assert unique is True, (
            f"{name} is not UNIQUE in the migration. It is a duplicate-prevention "
            "constraint, and without uniqueness it prevents nothing."
        )
